AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  myLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested-stack/mylambda.yaml
      
