AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  sampleLambda:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ../lambda/sample_lambda/src
        Handler: lambda_function.lambda_handler
        FunctionName: my-sample-lambda
        Runtime: python3.7
        Description: "This is a lambda function"
        MemorySize: 128
        Timeout: 60
    
